### ISSUE TITLE
Add instructions to use library without dependency injection

### ISSUE THREAD

**Issue by bryandh** [RoushTech/RollbarDotNet#29]
I'd like to be able to use this library in a .NET Core console application. However, I have no idea how to add Rollbar without a Startup.cs file.

Any suggestions?

**Comment by StrangeWill** [comment]
_Ideally_ you'd still want to use dependency injection on a console app.

You can do something like this (mind you I'm cramming this out in a notepad really fast so things may be off):

```
var configurationBuilder = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json");
var configuration = configurationBuilder.Build();

var rollbar = new Rollbar(
    new IBuilder[] {
        new ConfigurationBuilder(configuration),
        new EnvironmentBuilder(new SystemDateTime()), // SystemDateTime abstracts DateTime for mocking
        new ExceptionBuilder(),
        new NotifierBuilder()
    }
);

try
{
    throw new Exception("Testing");
}
catch(Exception exception)
{
    await rollbar.SendException(exception); //Err... everything is async, keep that in mind.
}
```

I'll see about writing some stuff into Readme regarding this.

**Comment by bryandh** [comment]
Hmm looks good.
However, your `ExceptionBuilder` class doesn't implement the `IBuilder` interface and can therefore not be added to the `IBuilder` array in your example.

**Comment by StrangeWill** [comment]
Ah yeah ExceptionBuilder is hardcoded, hmm I should probably see about making that injected too so you can extend it easily...

**Comment by StrangeWill** [comment]
Done in d568a2d7f022b9e8b235f23cdea71d41e1d257a2
