### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by elahurd925** [RoushTech/RollbarDotNet#40]
When trying to call `Rollbar.SendMessage`, I'm getting a `NullReferenceException`. Using `Rollbar.SendException` works fine. I think it may be due to `Body.Message` not being initialized, then `payload.Data.Body.Message.Body = message` is called. I noticed that a new `Body` is initialized in the `Data` constructor, but no `Message` is initialized in the `Body` constructor.

For what it's worth, I've been trying to use this in a custom `ILogger`. I was thinking that I might have configured something wrong, but I noticed that missing initialization so I thought I'd bring it up.

Thanks!

**Comment by StrangeWill** [comment]
I can't even be certain I have any tests on SendMessage, I'll see about getting that in 0.5.0 (and I'm going to push to have that out this weekend due to changes coming in today).

**Comment by StrangeWill** [comment]
Fixed in PR #41, going to see about releasing that tonight or at latest tomorrow.

**Comment by StrangeWill** [comment]
Released 0.5.0, let me know if you have any further issues. Let me know if upgrading to 0.5.0 is disruptive for you, I may backport this fix to a 0.4.1 patch if needed (should be pretty easy though).
