### ISSUE TITLE
SendException and SendMessage fails for content type: application/json

### ISSUE THREAD

**Issue by daithimaolain** [RoushTech/RollbarDotNet#54]
Exception Message: "Incorrect Content-Type: application/json; charset=UTF-8"
   StackTrace	
```
   at Microsoft.AspNetCore.Http.Features.FormFeature.ReadForm()
   at RollbarDotNet.Builder.RequestBuilder.BuildRequest(Request request)
   at RollbarDotNet.Builder.RequestBuilder.Execute(Payload payload)
   at RollbarDotNet.Rollbar.ExecuteBuilders(Payload payload)
   at RollbarDotNet.Rollbar.SetupPayload(RollbarLevel level)
   at RollbarDotNet.Rollbar.<SendException>d__14.MoveNext()
```

This could be because I am calling SendException from custom middleware.

Thanks.

**Comment by StrangeWill** [comment]
I just re-ran the tests for 0.5.2 and am currently getting passed tests with messages, so Rollbar didn't "close" any oddities with the headers being sent. Here is the output of the tests when generating a 401 unauthorized response:

```
System.Net.Http.HttpRequestException : StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
      {
        Connection: keep-alive
        Date: Fri, 21 Apr 2017 15:10:42 GMT
        Server: nginx
        Access-Control-Allow-Origin: *
        Access-Control-Allow-Credentials: true
        X-Response-Time: 1ms
        Content-Length: 51
        Content-Type: application/json; charset=utf-8
      }
```

Content-type of application/json _is_ being accepted. Any chance you can check the HttpRequestException StreamContent and get the body that the server is responding with?

Do you happen to be working in a building that has some sort of web filtering (I've had this throw me for a loop before and cause weird unexpected errors like this)?

**Comment by StrangeWill** [comment]
> This could be because I am calling SendException from custom middleware.

Actually entirely possible that this is the cause -- I'm wondering if something isn't available that RollbarDotNet's `BuildRequest` function is expecting, because it crawls all over the context trying to gather information about the current request.

**Comment by StrangeWill** [comment]
Seems to be caused when trying to access `context.Request.Form`

Only reproduction I can find of this issue is here: https://github.com/aspnet/Security/issues/1069 and here: https://github.com/JeffreySu/WeiXinMPSDK/issues/283, the second link suggests we can add a second check to the post check to validate there _are_ form fields available.

I'll see about getting this done and out later today @daithimaolain.

**Comment by StrangeWill** [comment]
0.5.2 has been published and fixes this bug.
